## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += dom_range

dom_range_EXTENDS = typelib
dom_range_INCS = \
    ../base
dom_range_SOURCES = \
    nsIDOMRange.idl

include $(FILE_SUB_FOOTER)
