/* Static portion of defines for the OS/2 platform.
 * Pulled in by generated js-confdefs.h. */

#define CPP_THROW_NEW throw()
#define D_INO d_ino
#define EDITLINE 1
#define HAVE_CPP_AMBIGUITY_RESOLVING_USING 1
#define HAVE_CPP_DYNAMIC_CAST_TO_VOID_PTR 1
#define HAVE_CPP_PARTIAL_SPECIALIZATION 1
#define HAVE_CPUID_H 1
#define HAVE_DIRENT_H 1
#define HAVE_ENDIAN_H 1
#define HAVE_FCHMOD 1
#define HAVE_FLOCKFILE 1
#define HAVE_GETC_UNLOCKED 1
#define HAVE_GETOPT_H 1
#define HAVE_GETPAGESIZE 1
#define HAVE_I18N_LC_MESSAGES 1
#define HAVE_IO_H 1
#define HAVE_LCHOWN 1
#define HAVE_LOCALECONV 1
#define HAVE_LOCALECONV 1
#define HAVE_LOCALTIME_R 1
#define HAVE_MACHINE_ENDIAN_H 1
#define HAVE_MALLOC_H 1
#define HAVE_MBRTOWC 1
#define HAVE_MEMALIGN 1
#define HAVE_MEMMOVE 1
#define HAVE_MEMORY_H 1
#define HAVE_NL_TYPES_H 1
#define HAVE_POSIX_MEMALIGN 1
#define HAVE_RANDOM 1
#define HAVE_RINT 1
#define HAVE_SBRK 1
#define HAVE_SETLOCALE 1
#define HAVE_SIGINFO_T 1
#define HAVE_SNPRINTF 1
#define HAVE_SSIZE_T 1
#define HAVE_STATVFS 1
#define HAVE_STDCALL 1
#define HAVE_STRERROR 1
#define HAVE_STRNDUP 1
#define HAVE_STRTOK_R 1
#define HAVE_ST_BLKSIZE 1
#define HAVE_SYS_BITYPES_H 1
#define HAVE_SYS_CDEFS_H 1
#define HAVE_SYS_STATFS_H 1
#define HAVE_SYS_STATVFS_H 1
#define HAVE_SYS_VFS_H 1
#define HAVE_THREAD_TLS_KEYWORD 1
#define HAVE_UINT 1
#define HAVE_UNISTD_H 1
#define HAVE_VALLOC 1
#define HAVE_VA_COPY 1
#define HAVE_WCRTOMB 1
#define HAVE__UNWIND_BACKTRACE 1
#define HAVE___CXA_DEMANGLE 1
#define JSGC_INCREMENTAL 1
#define JS_ALIGN_OF_POINTER 4
#define JS_BITS_PER_WORD_LOG2 5
#define JS_BYTES_PER_DOUBLE 8
#define JS_CPU_X86 1
#define JS_DEFAULT_JITREPORT_GRANULARITY 3
#define JS_MONOIC 1
#define JS_NUNBOX32 1
#define JS_POLYIC 1
#define MALLOC_H <malloc.h>
#define MOZ_DEBUG_SYMBOLS 1
#define MOZ_DLL_SUFFIX ".dll"
#define MOZ_OS2_HIGH_MEMORY 1
#define NEED_CPP_UNUSED_IMPLEMENTATIONS 1
#define NEW_H <new>
#define NS_ALWAYS_INLINE __attribute__((always_inline))
#define NS_ATTR_MALLOC __attribute__((malloc))
#define NS_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#define OS2 1
#define OS2EMX_PLAIN_CHAR 1
#define STDC_HEADERS 1
#define VA_COPY va_copy
#define XP_OS2 1
#define X_DISPLAY_MISSING 1
