## @file
# Module makefile
#

SUB_DEPTH = ../../../..
include $(KBUILD_PATH)/subheader.kmk

INSTALLS += nssdev_private_exports

nssdev_private_exports_INST     = private/nss/
nssdev_private_exports_SOURCES  = \
    ckhelper.h \
    devm.h \
    devtm.h \
    devt.h \
    dev.h \
    nssdevt.h \
    nssdev.h

LIBRARIES += nssdev

nssdev_TEMPLATE     = NssLib
nssdev_SOURCES      = \
    devslot.c \
    devtoken.c \
    devutil.c \
    ckhelper.c

include $(FILE_SUB_FOOTER)
