## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += dom_apps

dom_apps_EXTENDS = typelib
dom_apps_INCS = \
    ../base \
    ../events
dom_apps_SOURCES = \
    mozIApplication.idl \
    nsIDOMApplicationRegistry.idl \
    nsIDOMApplicationRegistry2.idl \
    nsIAppsService.idl \
    nsIDOMMozApplicationEvent.idl

include $(FILE_SUB_FOOTER)
