## @file
# Module makefile
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += intl

intl_EXTENDS = typelib
intl_DEFPATH := $(PATH_SUB_CURRENT)/public
intl_SOURCES = \
    nsIStringBundle.idl \
    nsIStringBundleOverride.idl

include $(FILE_SUB_FOOTER)
