## @file
# Module makefile
#

SUB_DEPTH = ../../../..
include $(KBUILD_PATH)/subheader.kmk

INSTALLS += pkcs12_exports

pkcs12_exports_INST     = public/nss/
pkcs12_exports_SOURCES  = \
    pkcs12t.h \
    pkcs12.h \
    p12plcy.h \
    p12.h \
    p12t.h

LIBRARIES += pkcs12

pkcs12_TEMPLATE     = NssLib
pkcs12_SOURCES      = \
    p12local.c \
    p12creat.c \
    p12dec.c \
    p12plcy.c \
    p12tmpl.c \
    p12e.c \
    p12d.c

include $(FILE_SUB_FOOTER)
