## @file
# Module makefile
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

INSTALLS += gkipc_exports_mozilla_layout

gkipc_exports_mozilla_layout_INST = include/mozilla/layout/
gkipc_exports_mozilla_layout_SOURCES = \
    RenderFrameChild.h \
    RenderFrameParent.h \
    RenderFrameUtils.h

include $(FILE_SUB_FOOTER)
