/* Static portion of defines for the OS/2 platform.
 * Included by generated mozilla-config.h. */

#define ACCESSIBILITY 1
#define ATTRIBUTE_ALIGNED_MAX 16
#define BUILD_CTYPES 1
#define D_INO d_ino
#define ENABLE_SYSTEM_EXTENSION_DIRS 1
#define HAVE_CPUID_H 1
#define HAVE_DIRENT_H 1
#define HAVE_FCHMOD 1
#define HAVE_FLOCKFILE 1
#define HAVE_FONTCONFIG_FCFREETYPE_H 1
#define HAVE_FT_BITMAP_SIZE_Y_PPEM 1
#define HAVE_FT_GLYPHSLOT_EMBOLDEN 1
#define HAVE_FT_LOAD_SFNT_TABLE 1
#define HAVE_FT_SELECT_SIZE 1
#define HAVE_GETOPT_H 1
#define HAVE_I18N_LC_MESSAGES 1
#define HAVE_INTTYPES_H 1
#define HAVE_IO_H 1
#define HAVE_ISATTY 1
#define HAVE_LANGINFO_CODESET 1
#define HAVE_LCHOWN 1
#define HAVE_LOCALECONV 1
#define HAVE_LOCALTIME_R 1
#define HAVE_MALLOC_H 1
#define HAVE_MEMALIGN 1
#define HAVE_MEMMOVE 1
#define HAVE_MEMORY_H 1
#define HAVE_NL_TYPES_H 1
#define HAVE_POSIX_MEMALIGN 1
#define HAVE_RANDOM 1
#define HAVE_RINT 1
#define HAVE_SETBUF 1
#define HAVE_SIGINFO_T 1
#define HAVE_SNPRINTF 1
#define HAVE_SSIZE_T 1
#define HAVE_STDCALL 1
#define HAVE_STDINT_H 1
#define HAVE_STRERROR 1
#define HAVE_STRNDUP 1
#define HAVE_STRTOK_R 1
#define HAVE_ST_BLKSIZE 1
#define HAVE_SYS_BITYPES_H 1
#define HAVE_SYS_CDEFS_H 1
#define HAVE_SYS_STATFS_H 1
#define HAVE_SYS_STATVFS_H 1
#define HAVE_THREAD_TLS_KEYWORD 1
#define HAVE_UINT 1
#define HAVE_UINT64_T 1
#define HAVE_UNISTD_H 1
#define HAVE_VALLOC 1
#define HAVE_VA_COPY 1
#define HAVE__UNWIND_BACKTRACE 1
#define HAVE___CXA_DEMANGLE 1
#define IBMBIDI 1
#define JSGC_INCREMENTAL 1
#define JS_DEFAULT_JITREPORT_GRANULARITY 3
#define LIBJPEG_TURBO_X86_ASM 1
#define MALLOC_H <malloc.h>
#define MOZ_CRASHREPORTER_ENABLE_PERCENT 100
#define MOZ_DEBUG_SYMBOLS 1
#define MOZ_FEEDS 1
#define MOZ_LOGGING 1
#define MOZ_MEDIA 1
#define MOZ_OS2_HIGH_MEMORY 1
#define MOZ_PDF_PRINTING 1
#define MOZ_PLACES 1
#define MOZ_PROFILELOCKING 1
#define MOZ_SAMPLE_TYPE_FLOAT32 1
#define MOZ_SPEEX_RESAMPLER 1
#define MOZ_SYDNEYAUDIO 1
#define MOZ_TREE_CAIRO 1
#define MOZ_TREE_PIXMAN 1
#define MOZ_URL_CLASSIFIER 1
#define MOZ_VORBIS 1
#define MOZ_VP8 1
#define MOZ_XTF 1
#define NO_X11 1
#define NS_ALWAYS_INLINE __attribute__((always_inline))
#define NS_ATTR_MALLOC __attribute__((malloc))
#define NS_PRINTING 1
#define NS_PRINT_PREVIEW 1
#define NS_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#define OS2 1
#define OS2EMX_PLAIN_CHAR 1
#define STDC_HEADERS 1
#define VA_COPY va_copy
#define VPX_X86_ASM 1
#define X_DISPLAY_MISSING 1
