## @file
# Module makefile
#

SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

INCLUDE_SUBDIRS = \
    base \
    cookie \
    dns \
    socket \
    mime \
    streamconv \
    cache \
    protocol \
    system \
    ipc \
    build

ifdef NECKO_WIFI
INCLUDE_SUBDIRS += wifi
endif

include $(FILE_SUB_FOOTER)
