## @file
# Module makefile
#

SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

INCLUDE_SUBDIRS = \
    base \
    dns \
    mime \
    protocol \
    socket \
    ipc

include $(FILE_SUB_FOOTER)
