## @file
# Module makefile
#

SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += profile

profile_EXTENDS = typelib
profile_DEFPATH := $(PATH_SUB_CURRENT)/public
profile_SOURCES = \
    nsIProfile.idl \
    nsIProfileChangeStatus.idl \
    nsIProfileUnlocker.idl

include $(FILE_SUB_FOOTER)
