## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += dom_canvas

dom_canvas_EXTENDS = typelib
dom_canvas_SOURCES = \
    nsIDOMCanvasRenderingContext2D.idl \
    nsIDOMWebGLRenderingContext.idl

include $(FILE_SUB_FOOTER)
