## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += necko_res

necko_res_EXTENDS = typelib
necko_res_SOURCES = \
    nsIResProtocolHandler.idl

include $(FILE_SUB_FOOTER)
