## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += dom_stylesheets

dom_stylesheets_EXTENDS = typelib
dom_stylesheets_INCS = \
    ../base
dom_stylesheets_SOURCES = \
    nsIDOMMediaList.idl \
    nsIDOMStyleSheet.idl \
    nsIDOMStyleSheetList.idl

include $(FILE_SUB_FOOTER)
