## @file
# Module makefile
#

SUB_DEPTH = ../../../..
include $(KBUILD_PATH)/subheader.kmk

INSTALLS += cryptohi_exports

cryptohi_exports_INST     = public/nss/
cryptohi_exports_SOURCES  = \
    cryptohi.h \
    cryptoht.h \
    key.h \
    keyhi.h \
    keyt.h \
    keythi.h \
    sechash.h

LIBRARIES += cryptohi

cryptohi_TEMPLATE     = NssLib
cryptohi_SOURCES      = \
    sechash.c \
    seckey.c \
    secsign.c \
    secvfy.c \
    dsautil.c

include $(FILE_SUB_FOOTER)
