## @file
# Module makefile
#

SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

INCLUDE_SUBDIRS += \
    base \
    canvas \
    events \
    html/content \
    html/document \
    smil \
    xul \
    xbl

ifdef MOZ_MEDIA
INCLUDE_SUBDIRS += media
endif

include $(FILE_SUB_FOOTER)
