## @file
# Module makefile
#

SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

INCLUDE_SUBDIRS += \
    base \
    events \
    html/content \
    html/document \
    xul \
    xbl

include $(FILE_SUB_FOOTER)
