## @file
# Module makefile
#

SUB_DEPTH = ../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += zlib

zlib_TEMPLATE = NssLib
zlib_DEFS     = verbose=-1
zlib_SOURCES  = \
    adler32.c \
    compress.c \
    crc32.c \
    deflate.c \
    gzclose.c \
    gzlib.c \
    gzread.c \
    gzwrite.c \
    infback.c \
    inffast.c \
    inflate.c \
    inftrees.c \
    trees.c \
    uncompr.c \
    zutil.c

include $(FILE_SUB_FOOTER)
