## @file
# Module makefile
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += dom_media

dom_media_EXTENDS = typelib
dom_media_SOURCES = \
    nsIDOMMediaStream.idl \
    nsIDOMNavigatorUserMedia.idl

INSTALLS += dom_media_exports_mozilla

dom_media_exports_mozilla_INST = include/mozilla/dom/file/
dom_media_exports_mozilla_SOURCES = \
    MediaManager.h

include $(FILE_SUB_FOOTER)
