## @file
# Module makefile
#

SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += startupcache

startupcache_EXTENDS = typelib
startupcache_SOURCES = \
    nsIStartupCache.idl

INSTALLS += startupcache_exports_mozilla_scache

startupcache_exports_mozilla_scache_INST = include/mozilla/scache/
startupcache_exports_mozilla_scache_SOURCES = \
    StartupCache.h \
    StartupCacheUtils.h

include $(FILE_SUB_FOOTER)
