## @file
# Module makefile
#

SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

INCLUDE_SUBDIRS = \
    style \
    base \
    generic \
    forms \
    xul/base/public \
    xul/base/src \
    ipc \

INCLUDE_SUBDIRS += \
    build

include $(FILE_SUB_FOOTER)
