## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += pipboot

pipboot_EXTENDS = typelib
pipboot_DEFPATH := $(PATH_SUB_CURRENT)/public
pipboot_INCS    = \
    $(PATH_ROOT)/dom/base
pipboot_SOURCES = \
    nsISecurityWarningDialogs.idl \
    nsISSLStatusProvider.idl \
    nsIBufEntropyCollector.idl \
    nsISecurityUITelemetry.idl

include $(FILE_SUB_FOOTER)
