## @file
# Module makefile
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += dom_camera

dom_camera_EXTENDS = typelib
dom_camera_INCS    = \
    ../base \
    ../interfaces/base \
    ../interfaces/events \
    ../media
dom_camera_SOURCES = \
    nsIDOMNavigatorCamera.idl \
    nsIDOMCameraManager.idl

INSTALLS += domcamera_exports

domcamera_exports_INST = include/
domcamera_exports_SOURCES = \
    DOMCameraManager.h

include $(FILE_SUB_FOOTER)
