## @file
# Module makefile
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

INSTALLS += domworkers_exports_mozilla_dom_workers

domworkers_exports_mozilla_dom_workers_INST = include/mozilla/dom/workers/
domworkers_exports_mozilla_dom_workers_SOURCES = \
    Workers.h

INSTALLS += domworkers_exports_mozilla_dom_workers_bindings

domworkers_exports_mozilla_dom_workers_bindings_INST = include/mozilla/dom/workers/bindings/
domworkers_exports_mozilla_dom_workers_bindings_SOURCES = \
    DOMBindingBase.h \
    EventListenerManager.h \
    EventTarget.h \
    WorkerFeature.h \
    XMLHttpRequestEventTarget.h \
    XMLHttpRequestUpload.h \
    XMLHttpRequest.h

include $(FILE_SUB_FOOTER)
