## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += xultmpl

xultmpl_EXTENDS = typelib
xultmpl_DEFPATH := $(PATH_SUB_CURRENT)/public
xultmpl_INCS    = \
    $(PATH_ROOT)/dom/interfaces/base
xultmpl_SOURCES = \
    nsIXULSortService.idl \
    nsIXULTemplateBuilder.idl \
    nsIXULBuilderListener.idl \
    nsIXULTemplateQueryProcessor.idl \
    nsIXULTemplateResult.idl \
    nsIXULTemplateRuleFilter.idl

include $(FILE_SUB_FOOTER)
