## @file
# Module makefile
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

INSTALLS += gkconxbl_exports

gkconxbl_exports_INST = include/
gkconxbl_exports_DEFPATH := $(PATH_SUB_CURRENT)/src
gkconxbl_exports_SOURCES = \
    nsBindingManager.h \
    nsXBLBinding.h

include $(FILE_SUB_FOOTER)
