## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += nkdata_s

nkdata_s_EXTENDS    = netwerk_s_base
nkdata_s_EXTENDS_BY = appending
nkdata_s_SOURCES    = \
    nsDataHandler.cpp \
    nsDataChannel.cpp

include $(FILE_SUB_FOOTER)
