## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += nkdevice_s

nkdevice_s_EXTENDS    = LibXulChromium
nkdevice_s_EXTENDS    = netwerk_s_base
nkdevice_s_EXTENDS_BY = appending
nkdevice_s_SOURCES    = \
    nsDeviceChannel.cpp \
    nsDeviceProtocolHandler.cpp

ifeq ($(MOZ_WIDGET_TOOLKIT),android)
$(error Port me! See Makefile.in)
endif

ifeq ($(MOZ_WIDGET_TOOLKIT),gonk)
$(error Port me! See Makefile.in)
endif

include $(FILE_SUB_FOOTER)
