## @file
# Module makefile
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += embed_base

embed_base_EXTENDS = typelib
embed_base_SOURCES = \
    nsIWindowCreator.idl \
    nsIWindowCreator2.idl \
    nsIWindowProvider.idl \
    nsIDialogCreator.idl

INSTALLS += embed_base_exports

embed_base_exports_INST = include/
embed_base_exports_SOURCES = \
    nsEmbedCID.h

include $(FILE_SUB_FOOTER)
