## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += necko_file

necko_file_EXTENDS = typelib
necko_file_SOURCES = \
    nsIFileChannel.idl \
    nsIFileProtocolHandler.idl

LIBRARIES += nkfile_s

nkfile_s_EXTENDS    = netwerk_s_base
nkfile_s_EXTENDS_BY = appending
nkfile_s_SOURCES    = \
    nsFileProtocolHandler.cpp \
    nsFileChannel.cpp

include $(FILE_SUB_FOOTER)
