## @file
# Module makefile
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

INSTALLS += gkconsmil_exports

gkconsmil_exports_INST = include/
gkconsmil_exports_SOURCES = \
    nsISMILAnimationElement.h \
    nsISMILAttr.h \
    nsISMILType.h \
    nsSMILAnimationController.h \
    nsSMILCompositorTable.h \
    nsSMILCSSProperty.h \
    nsSMILKeySpline.h \
    nsSMILMappedAttribute.h \
    nsSMILMilestone.h \
    nsSMILTimeContainer.h \
    nsSMILTypes.h

include $(FILE_SUB_FOOTER)
