## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

INSTALLS += appstartup_exports_mozilla

appstartup_exports_mozilla_INST = include/mozilla/
appstartup_exports_mozilla_SOURCES = \
    StartupTimeline.h

include $(FILE_SUB_FOOTER)
