## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += dom_xbl

dom_xbl_EXTENDS = typelib
dom_xbl_INCS = \
    ../base
dom_xbl_SOURCES = \
    nsIDOMDocumentXBL.idl

include $(FILE_SUB_FOOTER)
