## @file
# Module makefile
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

INSTALLS += gfx2d_exports_mozilla_gfx

gfx2d_exports_mozilla_gfx_INST = include/mozilla/gfx/
gfx2d_exports_mozilla_gfx_SOURCES = \
    2D.h \
    BasePoint.h \
    BasePoint3D.h \
    BasePoint4D.h \
    BaseMargin.h \
    BaseRect.h \
    BaseSize.h \
    Blur.h \
    PathHelpers.h \
    Point.h \
    Matrix.h \
    Rect.h \
    Types.h \
    UserData.h

include $(FILE_SUB_FOOTER)
