## @file
# Module makefile
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

INCLUDE_SUBDIRS = \
    document

ifdef MOZ_XUL
INCLUDE_SUBDIRS += templates
endif

include $(FILE_SUB_FOOTER)
