## @file
# Module makefile
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

#
# Include sub-makefiles.
#
include $(PATH_SUB_CURRENT)/ds/Makefile.kmk
include $(PATH_SUB_CURRENT)/libc/Makefile.kmk

include $(FILE_SUB_FOOTER)
