## @file
# Module makefile
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += idl-parser

idl-parser_SOURCE = header.py typelib.py xpidl.py $(PLY_PROGS)
idl-parser_OUTPUT = xpidllex.py xpidlyacc.py

idl-parser_INTERMEDIATE = xpidl_debug $(patsubst %.py,%.pyc,$(idl-parser_TARGET))

idl-parser_COMMAND = \
    cd $(outdir) && $(PYTHON_PATH) $(PLY_INCLUDE) $(defpath)/header.py --cachedir=. --regen

include $(FILE_SUB_FOOTER)
