## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += dom_offline

dom_offline_EXTENDS = typelib
dom_offline_INCS = \
    ../base
dom_offline_SOURCES = \
    nsIDOMOfflineResourceList.idl \
    nsIDOMLoadStatus.idl

include $(FILE_SUB_FOOTER)
