## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += dom_devicestorage

dom_devicestorage_EXTENDS = typelib
dom_devicestorage_INCS = \
    ../base \
    ../events
dom_devicestorage_SOURCES = \
    nsIDOMDeviceStorage.idl \
    nsIDOMDeviceStorageStat.idl \
    nsIDOMDeviceStorageCursor.idl \
    nsIDOMNavigatorDeviceStorage.idl \
    nsIDOMDeviceStorageChangeEvent.idl

include $(FILE_SUB_FOOTER)
