## @file
# Module makefile
#

SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

INCLUDE_SUBDIRS += \
    interfaces/base \
    interfaces/core \
    interfaces/css \
    interfaces/events \
    interfaces/geolocation \
    interfaces/stylesheets \
    interfaces/xul \
    bindings \
    ipc

include $(FILE_SUB_FOOTER)
