## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

INSTALLS += jsdomgeolocation_exports

jsdomgeolocation_exports_INST = include/
jsdomgeolocation_exports_SOURCES = \
    nsGeoPosition.h \
    nsGeoPositionIPCSerialiser.h

include $(FILE_SUB_FOOTER)
