## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += content_htmldoc

content_htmldoc_EXTENDS = typelib
content_htmldoc_DEFPATH := $(PATH_SUB_CURRENT)/public
content_htmldoc_SOURCES = \
    nsIImageDocument.idl

INSTALLS += gkconhtmldoc_exports

gkconhtmldoc_exports_INST = include/
gkconhtmldoc_exports_SOURCES = \
    $(addprefix src/, \
        nsIHTMLDocument.h \
    )

include $(FILE_SUB_FOOTER)
