## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += dom_xpath

dom_xpath_EXTENDS = typelib
dom_xpath_INCS = \
    ../base \
    ../core
dom_xpath_SOURCES = \
    nsIDOMXPathEvaluator.idl \
    nsIDOMXPathExpression.idl \
    nsIDOMXPathNamespace.idl \
    nsIDOMXPathNSResolver.idl \
    nsIDOMXPathResult.idl \
    nsIDOMNSXPathExpression.idl

include $(FILE_SUB_FOOTER)
