## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += dom_traversal

dom_traversal_EXTENDS = typelib
dom_traversal_INCS = \
    ../base
dom_traversal_SOURCES = \
    nsIDOMNodeFilter.idl \
    nsIDOMNodeIterator.idl \
    nsIDOMTreeWalker.idl

include $(FILE_SUB_FOOTER)
