## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

INSTALLS += sqlite3_exports

sqlite3_exports_INST = include/
sqlite3_exports_SOURCES = \
    sqlite3.h

include $(FILE_SUB_FOOTER)
