## @file
# Module makefile
#

SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

INCLUDE_SUBDIRS = \
    idl-parser \
    typelib \
    string \
    glue \
    base \
    ds \
    io \
    components \
    threads \
    reflect \
    system \
    ../chrome \
    build

include $(FILE_SUB_FOOTER)
