## @file
# Module makefile
#

SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

#
# Include sub-makefiles.
#
include $(PATH_SUB_CURRENT)/config/Makefile.kmk
include $(PATH_SUB_CURRENT)/pr/Makefile.kmk
include $(PATH_SUB_CURRENT)/lib/Makefile.kmk

include $(FILE_SUB_FOOTER)
