## @file
# Module makefile
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

INSTALLS += chardet_exports

chardet_exports_INST = include/
chardet_exports_DEFPATH := $(PATH_SUB_CURRENT)/public
chardet_exports_SOURCES = \
    nsDetectionConfident.h \
    nsICharsetDetectionObserver.h \
    nsICharsetDetector.h \
    nsIStringCharsetDetector.h

include $(FILE_SUB_FOOTER)
