## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += commandlines

commandlines_EXTENDS = typelib
commandlines_SOURCES = \
    nsICommandLine.idl \
    nsICommandLineHandler.idl \
    nsICommandLineRunner.idl \
    nsICommandLineValidator.idl

include $(FILE_SUB_FOOTER)
