## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += dom_loadsave

dom_loadsave_EXTENDS = typelib
dom_loadsave_INCS = \
    ../base \
    ../events
dom_loadsave_SOURCES = \
    nsIDOMLSProgressEvent.idl

include $(FILE_SUB_FOOTER)
