## @file
# Module makefile
#

SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

INSTALLS += view_exports

view_exports_INST = include/
view_exports_DEFPATH := $(PATH_SUB_CURRENT)/public
view_exports_SOURCES = \
    nsIView.h \
    nsIViewManager.h \
    nsViewsCID.h \
    nsIScrollPositionListener.h

include $(FILE_SUB_FOOTER)
