## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += dom_contacts

dom_contacts_EXTENDS = typelib
dom_contacts_INCS = \
    ../base \
    ../events
dom_contacts_SOURCES = \
    nsIDOMContactProperties.idl \
    nsIDOMContactManager.idl \
    nsIDOMMozContactChangeEvent.idl

include $(FILE_SUB_FOOTER)
