## @file
# Module makefile
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

USES += tasks

TASKS += dom_settings

dom_settings_EXTENDS = typelib
dom_settings_INCS = \
    ../base \
    ../events
dom_settings_SOURCES = \
    nsIDOMSettingsManager.idl \
    nsISettingsService.idl \
    nsIDOMMozSettingsEvent.idl

include $(FILE_SUB_FOOTER)
